"""empty message

Revision ID: 04ad30f9369b
Revises: 5dec2b37006b
Create Date: 2025-08-05 17:36:47.060921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ad30f9369b'
down_revision = '5dec2b37006b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['tag_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
