"""empty message

Revision ID: 090b8e4dab6d
Revises: 28e692de278e
Create Date: 2025-08-15 14:35:59.739874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090b8e4dab6d'
down_revision = '28e692de278e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'))
        # batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'))
        pass

    with op.batch_alter_table('post_user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
