"""empty message

Revision ID: 464cef8f60b9
Revises: 04ad30f9369b
Create Date: 2025-08-06 15:15:11.347111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464cef8f60b9'
down_revision = '04ad30f9369b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_tags_id', sa.String(length=255), nullable=False, comment='笔记标签'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.drop_column('post_tags_id')

    # ### end Alembic commands ###
