"""empty message

Revision ID: 5630f94e3315
Revises: 901bbf744a8d
Create Date: 2025-08-20 11:33:51.082442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5630f94e3315'
down_revision = '901bbf744a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.alter_column('post_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               existing_comment='笔记标题')
        batch_op.alter_column('post_category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               existing_comment='笔记分类')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.alter_column('post_category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               existing_comment='笔记分类')
        batch_op.alter_column('post_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               existing_comment='笔记标题')

    # ### end Alembic commands ###
