"""empty message

Revision ID: 5dec2b37006b
Revises: 870f03ab5303
Create Date: 2025-08-05 15:58:43.073699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dec2b37006b'
down_revision = '870f03ab5303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tag', schema=None) as batch_op:
        batch_op.alter_column('tag_count',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Integer(),
               comment='标签数量',
               existing_comment='标签出现数量',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tag', schema=None) as batch_op:
        batch_op.alter_column('tag_count',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='标签出现数量',
               existing_comment='标签数量',
               existing_nullable=False)

    # ### end Alembic commands ###
