"""empty message

Revision ID: 870f03ab5303
Revises: 
Create Date: 2025-08-05 15:55:20.131315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870f03ab5303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('post_id', sa.String(length=255), nullable=False, comment='笔记ID'),
    sa.Column('post_title', sa.String(length=255), nullable=False, comment='笔记标题'),
    sa.Column('post_content', sa.Text(), nullable=False, comment='笔记内容'),
    sa.Column('post_url', sa.String(length=255), nullable=False, comment='笔记链接'),
    sa.Column('post_date', sa.DateTime(), nullable=False, comment='笔记发布时间'),
    sa.Column('post_updated', sa.DateTime(), nullable=False, comment='笔记更新时间'),
    sa.Column('post_author_id', sa.String(length=255), nullable=False, comment='笔记作者ID'),
    sa.Column('post_category', sa.String(length=255), nullable=False, comment='笔记分类'),
    sa.Column('post_ip', sa.String(length=255), nullable=False, comment='笔记IP'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('post_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('tag_id', sa.String(length=255), nullable=False, comment='标签ID'),
    sa.Column('tag_name', sa.String(length=255), nullable=False, comment='标签名称'),
    sa.Column('tag_type', sa.String(length=255), nullable=False, comment='标签类型'),
    sa.Column('tag_count', sa.String(length=255), nullable=False, comment='标签出现数量'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户ID'),
    sa.Column('user_name', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('user_avatar', sa.String(length=255), nullable=False, comment='用户头像'),
    sa.Column('user_xsec_token', sa.String(length=255), nullable=False, comment='用户XSEC_TOKEN'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_interact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('post_id', sa.String(length=255), nullable=False, comment='笔记ID'),
    sa.Column('collected_count', sa.String(length=255), nullable=False, comment='笔记收藏数'),
    sa.Column('comment_count', sa.String(length=255), nullable=False, comment='笔记评论数'),
    sa.Column('share_count', sa.String(length=255), nullable=False, comment='笔记分享数'),
    sa.Column('liked_count', sa.String(length=255), nullable=False, comment='笔记点赞数'),
    sa.ForeignKeyConstraint(['post_id'], ['post_detail.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('post_id', sa.String(length=255), nullable=False, comment='笔记ID'),
    sa.Column('post_images', sa.Text(), nullable=True, comment='笔记图片'),
    sa.Column('post_videos', sa.Text(), nullable=True, comment='笔记视频'),
    sa.ForeignKeyConstraint(['post_id'], ['post_detail.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_media')
    op.drop_table('post_interact')
    op.drop_table('post_user')
    op.drop_table('post_tag')
    op.drop_table('post_detail')
    # ### end Alembic commands ###
