"""empty message

Revision ID: 901bbf744a8d
Revises: 090b8e4dab6d
Create Date: 2025-08-20 11:27:23.957695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '901bbf744a8d'
down_revision = '090b8e4dab6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_name', sa.String(length=255), nullable=False, comment='用户名称'),
    sa.Column('user_pwd', sa.String(length=255), nullable=False, comment='用户密码'),
    sa.Column('salt', sa.String(length=255), nullable=True, comment='salt'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.alter_column('post_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_comment='笔记内容')
        batch_op.alter_column('post_updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='笔记更新时间')
        batch_op.alter_column('post_at_user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               existing_comment='笔记被@用户ID')
        batch_op.alter_column('post_tags_id',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_comment='笔记标签')
        batch_op.alter_column('post_ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               existing_comment='笔记IP')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('post_ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               existing_comment='笔记IP')
        batch_op.alter_column('post_tags_id',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_comment='笔记标签')
        batch_op.alter_column('post_at_user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               existing_comment='笔记被@用户ID')
        batch_op.alter_column('post_updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='笔记更新时间')
        batch_op.alter_column('post_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_comment='笔记内容')

    op.drop_table('user')
    # ### end Alembic commands ###
