"""empty message

Revision ID: 9de31ca2a05b
Revises: bf0d10cdc187
Create Date: 2025-08-06 16:26:44.665445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de31ca2a05b'
down_revision = 'bf0d10cdc187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_at_user_id', sa.String(length=255), nullable=False, comment='笔记被@用户ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.drop_column('post_at_user_id')

    # ### end Alembic commands ###
