"""empty message

Revision ID: bf0d10cdc187
Revises: 464cef8f60b9
Create Date: 2025-08-06 15:24:41.864595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf0d10cdc187'
down_revision = '464cef8f60b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_share_url', sa.String(length=255), nullable=False, comment='笔记链接'))
        batch_op.drop_column('post_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='笔记链接'))
        batch_op.drop_column('post_share_url')

    # ### end Alembic commands ###
